Unable to find image 'quay.io/biocontainers/hisat2:2.2.1--h87f3376_5' locally
2.2.1--h87f3376_5: Pulling from biocontainers/hisat2
c1a16a04cedd: Already exists
4ca545ee6d5d: Already exists
02049f9d04b6: Pulling fs layer
02049f9d04b6: Verifying Checksum
02049f9d04b6: Download complete
02049f9d04b6: Pull complete
Digest: sha256:515195ae9f597450958126f509aa0f8e003e445089062e0e17e246ec4fec00e5
Status: Downloaded newer image for quay.io/biocontainers/hisat2:2.2.1--h87f3376_5
/bin/bash: line 0: export: `Workflow/comp_work_project/nf-core/bin': not a valid identifier
Settings:
  Output files: "hisat_build.*.ht2"
  Line rate: 6 (line is 64 bytes)
  Lines per side: 1 (side is 64 bytes)
  Offset rate: 4 (one in 16)
  FTable chars: 10
  Strings: unpacked
  Local offset rate: 3 (one in 8)
  Local fTable chars: 6
  Local sequence length: 57344
  Local sequence overlap between two consecutive indexes: 1024
  Endianness: little
  Actual local endianness: little
  Sanity checking: disabled
  Assertions: disabled
  Random seed: 0
  Sizeofs: void*:8, int:4, long:8, size_t:8
Input files DNA, FASTA:
  ./data/genome.fa
Error: could not open ./data/genome.fa
Total time for call to driver() for forward index: 00:00:00
Error: Encountered internal HISAT2 exception (#1)
Command: hisat2-build --wrapper basic-0 ./data/genome.fa hisat_build 
